# Generated by Django 6.0.7 on 2026-07-26 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0007_flashcardtopicreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payslip',
            field=models.ImageField(blank=True, null=True, upload_to='payslips/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
