# Generated by Django 6.0.7 on 2026-07-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0008_enrollment_payment_type_enrollment_payslip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
