# Generated by Django 6.0.7 on 2026-08-06 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0009_enrollment_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('lecture', 'Lecture Slides'), ('syllabus', 'Syllabus & Info'), ('assignment', 'Assignment / Worksheet'), ('reference', 'Reference Material'), ('video', 'Video / Audio Link'), ('other', 'Other Resource')], default='lecture', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='teacher_materials/')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='smartlearnApp.classroom')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
