# Generated by Django 6.0.7 on 2026-08-19 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0011_communitynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
