# Generated by Django 6.0.7 on 2026-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='member_limit',
            field=models.IntegerField(blank=True, help_text='Maximum number of students allowed (leave blank for unlimited)', null=True),
        ),
    ]
