# Generated by Django 6.0.7 on 2026-08-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0014_classroom_member_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit in minutes (leave blank for no limit)', null=True)),
                ('max_attempts', models.IntegerField(blank=True, help_text='Maximum number of attempts per student (leave blank for unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_settings', to='smartlearnApp.classroom')),
            ],
        ),
    ]
