# Generated by Django 6.0.7 on 2026-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0014_classroom_member_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
