# Generated by Django 6.0.7 on 2026-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0015_quizsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='topic',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
