# Generated by Django 6.0.7 on 2026-08-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0015_classroom_is_live'),
        ('smartlearnApp', '0016_quizattempt_topic'),
    ]

    operations = [
    ]
